name: Download and Unzip Dataset

on: [push, pull_request]

jobs:
  download_and_unzip:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle

    # Step 4: Set Kaggle credentials
    - name: Set Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    # Step 5: Download and unzip the dataset
    - name: Download and unzip dataset
      run: |
        mkdir -p data
        kaggle datasets download -d arashnic/fitbit -p data
        unzip data/*.zip -d data
        rm data/*.zip

    # Step 6: Debugging step to list files in data directory
    - name: List files in data directory
      run: ls -al data

    # Step 7: Debugging step to list files in repository root
    - name: List files in repository root
      run: ls -al