name: Download, Unzip, and Process Dataset

on: [push, pull_request]

jobs:
  process_dataset:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas

    # Step 4: Set Kaggle credentials
    - name: Set Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    # Step 5: Download and unzip the dataset
    - name: Download and unzip dataset
      run: |
        mkdir -p data
        kaggle datasets download -d arashnic/fitbit -p data
        unzip data/*.zip -d data
        rm data/*.zip

    # Step 6: Debugging step to list files in data directory
    - name: List files in data directory
      run: ls -al data

    # Step 7: Debugging step to list files in subdirectories of data
    - name: List files in subdirectories of data
      run: ls -al data/*

    # Step 8: Run the Python script to list directory structure and process CSV files
    - name: Run Python script
      run: python scripts/main.py

    # Step 9: Append the contents of /app/output.txt to README.md
    - name: Update README.md
      run: |
        echo -e "\n## Output\n" >> README.md
        cat /app/output.txt >> README.md

    # Step 10: Commit the changes to README.md
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README.md with output from workflow'
        git push

    # Step 11: Debugging step to list files in repository root
    - name: List files in repository root
      run: ls -al