name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t ml-fitbit-fitness-tracker .

    # Step 3: Set Kaggle credentials as environment variables
    - name: Set Kaggle credentials
      run: |
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV

    # Step 4: Download dataset from Kaggle
    - name: Download dataset
      run: |
        docker run --env KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} --env KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} ml-fitbit-fitness-tracker kaggle datasets download -d arashnic/fitbit --unzip -p data/

    # Step 5: Run the main Python script
    - name: Run Python script
      run: docker run ml-fitbit-fitness-tracker python scripts/main.py

    # Step 6: Print first rows of the dataset
    - name: Print first rows of the dataset
      run: docker run ml-fitbit-fitness-tracker python scripts/main.py

    # Step 7: Upload coverage badge
    - name: Upload coverage badge
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage-badge.svg