name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install kaggle

    # Step 4: Set Kaggle credentials as environment variables
    - name: Set Kaggle credentials
      run: |
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" > ~/.kaggle/kaggle.json
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    # Step 5: Download and unzip the dataset
    - name: Download and unzip dataset
      run: |
        mkdir -p data
        kaggle datasets download -d <dataset-identifier> -p data
        unzip data/*.zip -d data
        rm data/*.zip

    # Step 6: Run the Python script
    - name: Run Python script
      run: python scripts/main.py

    # Step 7: Debugging step to list files in workspace
    - name: List files in workspace
      run: ls -al ${{ github.workspace }}

    # Step 8: Update README.md with output
    - name: Update README.md
      run: |
        if [ -f output.txt ]; then
          head_output=$(cat output.txt)
          sed -i '/<!-- OUTPUT START -->/,/<!-- OUTPUT END -->/c\<!-- OUTPUT START -->\n```\n$head_output\n```\n<!-- OUTPUT END -->' README.md
        else
          echo "output.txt not found"
          exit 1
        fi

    # Step 9: Commit changes
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README.md with dataset head output'
        git push