name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t ml-fitbit-fitness-tracker .

    # Step 3: Set Kaggle credentials as environment variables
    - name: Set Kaggle credentials
      run: |
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV

    # Step 4: Run the Docker container
    - name: Run Docker container
      run: docker run --env KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} --env KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} ml-fitbit-fitness-tracker

    # Step 5: Upload coverage badge
    - name: Upload coverage badge
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage-badge.svg